FROM python:3.11-slim

# إعدادات البيئة
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# تحديث النظام وتثبيت أدوات مساعدة
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

# إنشاء مجلد العمل
WORKDIR /app

# نسخ المتطلبات
COPY requirements_full_v3.txt .

# تثبيت المكتبات
RUN pip install --upgrade pip && pip install -r requirements_full_v3.txt

# نسخ التطبيق
COPY . .

# فتح البورت
EXPOSE 8501

# تشغيل Streamlit
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
